name: Scheduled Audit
on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at 00:00
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
