name: Scheduled Build
on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at 00:00
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push layered pokedex
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: challengepokedex1/layered_pokedex
          context: ./layered_pokedex
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Build and push hexagonal pokedex
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: challengepokedex1/hexagonal_pokedex
          context: ./hexagonal_pokedex
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
